name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        distribution: 'mysql'
        mysql-version: '5.7'
        auto-start: true
        root-password: ${{ secrets.RootPassword }}
        
#    - name: set up mysql
#      uses: mirromutth/mysql-action@v1.1
#      with:
#        mysql version: '5.7' # Optional, default value is "latest". The version of the MySQL
#        mysql root password: ${{ secrets.RootPassword }} # Required if "mysql user" is empty, default is empty. The root superuser password
#    - name: Start MySQL
#      run: sudo service mysql restart
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: ROOT_DATABASE_PWD=${{ secrets.RootPassword }} DATABASE_DSN='root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local' go test -v ./...
