name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: shogo82148/actions-setup-mysql@v1
        with:
          distribution: 'mysql'
          mysql-version: '5.7'
          auto-start: true
          root-password: ${{ secrets.RootPassword }}


      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test $(go list ./... | grep -v /ch7/e2e)